server:
  port: 8081
spring:
  application:
    name: orderapp
  kafka:
    template:
      default-topic: producer-event
    consumer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      group-id: product-events-listener-group
